name: Clone BetterDiscord themes
run-name: ${{ github.actor }} cloning BetterDiscord themes
on: 
    workflow_dispatch:
    schedule:
        - cron: 0 0/1 * * *
    

jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repository
              run: |
                git clone ${{github.repositoryUrl}}
            - name: debug
              run: |
                tree -d
        

            

