name: Clone BetterDiscord themes
run-name: ${{ github.actor }} cloning BetterDiscord themes
on: 
    workflow_dispatch:
    schedule:
        - cron: 0 0/1 * * *
    

jobs:
    clone:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: creating a file
              run: echo HELLO > test.txt
            
            - name: Update resources
              uses: test-room-7/action-update-file@v1
              with:
                  file-path: test.txt
                  commit-msg: Update resources
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                
        

            

