name: Clone BetterDiscord themes
run-name: ${{ github.actor }} cloning BetterDiscord themes
on: 
    workflow_dispatch:
    schedule:
        - cron: 0 0/1 * * *
    

jobs:
    clone:
        runs-on: ubuntu-latest
        steps:
            - uses: wow-actions/update-file@v1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                path: README.md
                content: 'Updated by update-file action'
        

            

